### ISSUE TITLE
Probleme mit dem Import bei Bildern

### ISSUE THREAD

**Issue by vicotec** [contao-estatemanager/core#149]
## Installation:
- Contao 4.9.13
- Contao EstateManager Einrichtungsassistent 1.0.1
- Contao EstateManager Referenzen 1.0.4
- Contao EstateManager Virtuelle Tour 1.0.2

## Hosting:
- Alfahosting Multi XL
- PHP 7.4
- MySQL 5.7

## Import von:
- FLOWFACT
- Übertragung erfolgt über das OpenImmostandard in der Version 1.2.7

## Aufbau XML (gekürzt)
`<?xml` version="1.0" encoding="UTF-8" `standalone="yes"?>`
`<openimmo>`
    `<uebertragung art="ONLINE" umfang="TEIL" version="1.2.7" sendersoftware="FLOWFACT platform" senderversion="2.0"/>`
`    <anbieter>`
        `....`
        `<immobilie>`
           ` ....`
            `<anhaenge>`
                `<anhang location="EXTERN" gruppe="TITELBILD">`
                    `<anhangtitel>AdobeStock_95767010-min</anhangtitel>`
                    `<format>JPEG</format>`
                    `<daten>`
                        `<pfad><![CDATA[f6b5ca99-de73-4687-944a-513ccd16a944.jpeg]]></pfad>`
                    `</daten>`
                `</anhang>`
            `</anhaenge>`
           ` ....`
        `</immobilie>`
    `</anbieter>`
`</openimmo>`

## Bilder:
- zwischen 249 KB und 2,40 MB
- Auflösung 3000 x 3000 und 5386 x 3445
- alles .jpeg

## Problem:
Der Import aller Felder der XML funktioniert. Nur die Bilder werden nicht importiert. Dadurch wird z.B. bei der Verlinkung des Titelbildes nicht auf das Bild sondern auf den für das Objekt erstellten Ordner verwiesen, was im Frontend zu einem Fehler führt.
Ich habe für den Import mal in src/Resources/contao/classes/RealEstateImporter.php in Zeile 1323 den Log aktiviert und das ist das Ergebnis:

> Ursprung => files/flowfact_import/tmp/openimmo.xml

> Details => Image added:

> data =>    title: AdobeStock_95767010-min, fileName:

Es wird also einfach keine Bilddatei eingetragen, was dazu führt, dass die Einträge auf den Ordner und nicht auf eine Datei zeigen.

EDIT: Unter Umständen nicht irrelevant ist, dass die Contao-Webseite momentan noch hinter einem htaccess-Passwortschutz liegt.

**Comment by eki89** [comment]
Tatsächlich werden derzeit Werte, welche sich in einem CDATA-Block befinden, nicht korrekt eingelesen. Der Fehler sollte sich schnell beheben lassen und wird voraussichtlich mit dem nächsten Release veröffentlicht.

**Comment by doishub** [comment]
Fixed in `1.0.18`

**Comment by katgirl** [comment]
Ein Hinweis, dass das Verzeichnis public sein muss wäre auch schön ;-) Denn sonst klappt es bei mir auch nicht mit den Bildern.

**Comment by eki89** [comment]
Hallo katgirl, danke für den Hinweis. Wir veröffentlichen bald die vollständige Dokumentation und nehmen diese Information selbstverständlich mit auf.
