### ISSUE TITLE
Contao 4.11

### ISSUE THREAD

**Issue by katgirl** [contao-estatemanager/core#162]
Durch das Update auf 4.11.8 geht die Installation nicht mehr.

```bash
You have requested a non-existent parameter "kernel.root_dir". Did you mean one of these: "kernel.project_dir", "kernel.build_dir", "kernel.cache_dir", "kernel.logs_dir"?
```
Fehler ist in ```In ParameterBag.php line 93```

**Comment by doishub** [comment]
Hallo katgirl,

das Problem liegt derzeit an der Abhängigkeit des MCW-Bundles. Wir versuchen in einer der nächsten Versionen auf diese Abhängigkeit zu verzichten, da es hiermit in der Vergangenheit vermehrt zu Problemen gekommen ist. Ggf. findet sich aber auch eine geeignete Alternative, um das Problem schneller lösen zu können.

Siehe auch:
https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107

**Comment by katgirl** [comment]
Danke für das Feedback, noch ist die 4.9 ja da

**Comment by doishub** [comment]
Genau, wir arbeiten derzeit auch bereits an der 4.11 / PHP8 Kompatibilität.

Ich habe gerade mal den Tipp von Fritz in einer lokalen Installation getestet:
https://github.com/menatwork/contao-multicolumnwizard-bundle/issues/107#issuecomment-803645107

Damit konnte ich die 4.11 nun korrekt installieren:
```json
"symfony/http-kernel": "^4.4.29",
"symfony/event-dispatcher": "^4.4.27",
"symfony/config": "^v4.4.27",
"symfony/dependency-injection": "^v4.4.27",
"symfony/http-foundation": "^v4.4.29",
"symfony/translation": "^v4.4.27",
```

**Comment by zoglo** [comment]
Can be closed as the MultiColumnWizard has been updated for usage of PHP 8. 
The requirement has been introduced back in https://github.com/contao-estatemanager/core/releases/tag/1.0.27
