### ISSUE TITLE
Location filter ignores toggle filter values 

### ISSUE THREAD

**Issue by katgirl** [contao-estatemanager/core#167]
Wenn ich einen Filter mit Location und Raumzahl baue, dann entsteht folgendes Problem:

Wenn ich nach PLZ und 3 Raumwohnungen suche klappt alles.
Wenn ich jedoch nach Stadt und 3 Raumwohnungen suche, bekomme ich alle Angebote in der Stadt.

**Comment by eki89** [comment]
Hallo katgirl,
vielen Dank für die Fehlermeldung. Ich konnte den Fehler reproduzieren und habe diesen auch bereits behoben. Der Bugfix wird mit Version 1.0.20 voraussichtlich kommende Woche veröffentlicht.

**Comment by katgirl** [comment]
Denkt ihr noch dran die neue Version zu taggen ;-)
