### ISSUE TITLE
Incorrect formatting for the field  "sicherheitstechnik" 

### ISSUE THREAD

**Issue by NewmansHub** [contao-estatemanager/core#181]
For the field mentioned below, the wrong formatting is selected in the core. 

The field should be "unserialize".

https://github.com/contao-estatemanager/core/blob/2ee941ec46146805d291a0e7d44a1a06e6ddb196/src/Resources/contao/data/import_interface_mappings.php#L308

**Comment by zoglo** [comment]
Not a bug, rather a missing formatting field within *import_field_formats*.

The field format for this value will be added with the next release.
